# Welcome to Unified CI! This file contains the configuration for your project.
# You can edit it to customize the behavior of Unified CI.
# For more information, see https://github.com/ipdxco/unified-github-workflows

# The Unified CI templates which should be distributed to your project.
files: [".github/workflows/go-check.yml",".github/workflows/go-test.yml",".github/workflows/release-check.yml",".github/workflows/releaser.yml",".github/workflows/tagpush.yml"]
