version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - copyloopvar
    - depguard
    - exhaustive
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
  settings:
    depguard:
      rules:
        random:
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "golang.org/x/exp/rand"
              desc: use math/rand/v2
    # see https://github.com/ldez/usetesting/issues/10
    usetesting:
      context-background: false
      context-todo: false
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
